// ============================================================
// UNEC TEST SİSTEMİ — tests.js
// Öz suallarını buraya əlavə et.
//
// STRUKTUR:
//   QUESTION_BANK = {
//     "Fənn adı": [
//       { question: "...", options: ["A","B","C","D","E"], answer: 0 },
//       ...
//     ]
//   }
//
// answer → düzgün cavabın options massivindəki indeksi (0-dan başlayır)
// ============================================================

const QUESTION_BANK = {
  "İKT - Baza Kompüter Bilikləri": [
    { question: "Python-da bir dəyişənin məzmununu ekranda hansı əmrlə əks etdirmək olar?", options: ["output(x)", "print(x)", "write(x)", "echo(x)", "display(x)"], answer: 1 },
    { question: "Python-da dəyişən adı necə başlamalıdır?", options: ["Rəqəmlə", "- ilə", "Boşluq ilə", "Kiçik və ya böyük hərflə", "=@ işarəsi ilə"], answer: 3 },
    { question: "Python-da x = 5 verilənində x dəyişəni hansı tipdədir?", options: ["Float (onluq kəsr)", "List (siyahı)", "Boolean (məntiqi)", "Integer (tam ədəd)", "String (sətir)"], answer: 3 },
    { question: "Python-da hansı tip çevirmə əməliyyatı düzgündür?", options: ["float(10)", "int(5.6)", "str(10)", "Hamısı", "bool(10)"], answer: 3 },
    { question: "Aşağıdakılardan hansı Python-da sətir növüdür?", options: ["10.50", "None", "\"Hello\"", "5"], answer: 2 },
    { question: "Python hansı proqramlaşdırma dilinin kateqoriyasına aiddir?", options: ["Aşağı səviyyəli dil", "Assembler dili", "Maşın dili", "Yüksək səviyyəli dil", "Mətn emal dili"], answer: 3 },
    { question: "Python-da dəyişənin tipini necə öyrənmək olar?", options: ["typeof(x)", "checkType(x)", "varType(x)", "type(x)", "getType(x)"], answer: 3 },
    { question: "Python-un əsas xüsusiyyətlərindən biri nədir?", options: ["Yalnız kompilyasiya olunmuş proqramları dəstəkləyir", "Yalnız Windows-da işləyir", "Yalnız veb proqramlaşdırma üçün istifadə olunur", "Sadə və oxunaqlı sintaksisə malikdir", "Çox yavaşdır və istifadə olunmur"], answer: 3 },
    { question: "Aşağıdakılardan hansı ifadə sabitlər üçün doğrudur?", options: ["Python-da sabitləri təyin edən xüsusi açar söz yoxdur", "Sabitlər yalnız str tipində olur", "Sabitlər dəyişdirilə bilər", "Sabitlər const açar sözü ilə təyin olunur", "Sabitlər yalnız rəqəmlərlə təyin edilir"], answer: 0 },
    { question: "for dövründə dəyişənin adı nə ola bilər?", options: ["Yalnız hərf simvolları ola bilər", "Yalnız rəqəmlər ola bilər", "Yalnız xüsusi simvollar ola bilər", "İstənilən ad ola bilər", "Yalnız i ola bilər"], answer: 3 },
    { question: "Python-da hansı operatorlar müqayisə üçündür?", options: ["=, +, -, *", "<>, &, |, ^", "===, !== ", "++, --, ==, !=", "==, !=, <=, >="], answer: 4 },
    { question: "Python-da dəyişənə verilən yeni dəyəri yazmaq üçün hansı operator istifadə edilir?", options: ["*", "/", "-=", "+=", "="], answer: 4 },
    { question: "Python-un hansı əsas tətbiq sahəsi yoxdur?", options: ["Veb inkişafı", "Maşın öyrənməsi", "Oyun proqramlaşdırması", "Sürətli sistem proqramlaşdırması", "Data analitikası"], answer: 3 },
    { question: "Python kodunun icra edilməsi üçün nə lazımdır?", options: ["Yalnız brauzer", "Kompilyator", "İnterpretator", "Kod redaktoru", "Assembler"], answer: 2 },
    { question: "input() funksiyasından istifadə edərkən istifadəçinin daxil etdiyi dəyəri necə int tipinə çevirmək olar?", options: ["input() + 1", "input().int()", "convert(input())", "int(input())", "str(input())"], answer: 3 },
    { question: "Python-un hansı xüsusiyyəti var?", options: ["Dinamik olaraq tiplənir", "Məcburi olaraq dəyişən tiplərini təyin etmək lazımdır", "Yalnız konsol tətbiqləri yaza bilir", "Sətir sonlarında ; tələb edir", "Maşın dili ilə yazılır"], answer: 0 },
    { question: "Python-da hansı platformalarda proqram yaza bilərsiniz?", options: ["Yalnız Windows", "Yalnız mobil cihazlar", "Yalnız macOS", "Çoxplatformalıdır (Windows, Linux, macOS)", "Yalnız Linux"], answer: 3 },
    { question: "Hansı dəyişən adı səhvdir?", options: ["MY_VAR", "myVar", "1myVar", "my_var", "myVar1"], answer: 2 },
    { question: "Aşağıdakılardan hansı dəyişən adlandırması üçün düzgün yazılışdır?", options: ["my var", "class", "my-var", "_my_var", "2value"], answer: 3 },
    { question: "Python hansı fayl uzantısından istifadə edir?", options: [".java", ".cpp", ".py", ".html", ".cs"], answer: 2 },
    { question: "Python-da sətir necə təyin edilir?", options: ["()", "[]", "{}", "\" \" və ya ' '", "//"], answer: 3 },
    { question: "Aşağıdakılardan hansı Python-da ədəd tipini təmsil edir?", options: ["\"True\"", "10", "\"10\"", "'True'"], answer: 1 },
    { question: "Aşağıdakılardan hansı sürüşkən nöqtəli ədəd tipinin doğru yazılışıdır?", options: ["3.14", "\"3.14\"", "\"True\""], answer: 0 },
    { question: "Python dilində yazılmış ifadənin qiymətini tapın: x=56%56+12%3", options: ["1", "5", "3", "2", "0"], answer: 4 },
    { question: "Python dilində yazılmış ifadənin qiymətini tapın: x=12/6+23%3", options: ["5", "6", "7", "9", "4"], answer: 4 },
    { question: "Word-də Save as (Сохранить как/Fərqli saxla) əmrinin köməyi ilə nəyi dəyişmək olmaz?", options: ["faylın tipini", "sənədə şifrəsini", "faylın yerini", "faylın adını", "sənədin səhifə parametrlərini"], answer: 4 },
    { question: "Ctrl + S düymələr kombinasiyasının funksiyası nədir (MS Word)?", options: ["Sonuncu əməliyyatı ləğv edir", "Yeni sənəd açır", "Ləğv olunmuş əməliyyatı geri qaytarır", "Yaddaşda olan sənədi açır", "Sənədi yadda saxlayır"], answer: 4 },
    { question: "Aşağıdakılardan hansı Word proqramının yerinə yetirdiyi əməliyyat deyil?", options: ["Sənədə şəkil, cədvəl, qrafik və s. əlavə etmək", "Sənəddəki mətni sütunlara bölmək", "Sənədi şəkil formatında yadda saxlamaq", "Sənədin qeyd olunmuş hissəsinin nüsxəsini almaq", "Sənədin qeyd olunmuş hissəsini silmək"], answer: 2 },
    { question: "Save as (Сохранить как/Fərqli saxla əmri nə üçündür (Word)?", options: ["Sənədi Web-də saxlamaq", "Sənədi e-mail-lə göndərmək", "Sənədi xarici yaddaş qurğusunda saxlamaq", "Yeni sənəd yaratmaq", "Sənədi fərqli adla, fərqli yerdə, fərqli parametrlə saxlamaq"], answer: 4 },
    { question: "Yalnız oxumaq üçün açılmış sənədlə bağlı hansı işi görmək olmaz?", options: ["sənədi nəzərdən keçirmək", "sənədi elektron poçtla göndərmək", "düzəliş etmək", "sənədi çapa vermək", "sənəddə edilmiş düzəlişləri həmin faylda yadda saxlamaq"], answer: 4 },
    { question: "Clipboard (Буфер обмена/Mübadilə buferi) lent qrupuna aid olmayan əmr hansıdır (Word)?", options: ["Paste (Вставить)", "Format Painter (Копировать Формат)", "Copy (Копировать)", "Select (Выделить)", "Cut (Вырезать)"], answer: 3 },
    { question: "Sətri cədvəldən hansı yolla pozmaq olar (Word)?", options: ["Seçmək və klaviaturanın BackSpace düyməsini basmaqla.", "Seçmək və klaviaturanın Delete düyməsini basmaqla.", "Seçmək və klaviaturanın Alt+Ctrl düyməsini basmaqla.", "Seçmək və kəsib mübadilə buferinə atmaqla.", "Seçmək və klaviaturanın Alt+Delete düymələrini basmaqla."], answer: 0 },
    { question: "Abzasın sağ tərəfi düz, sol tərəfi çıxıntılı olubsa, onda nə üzrə düzləndirmə aparılıb (Word)?", options: ["heç bir düzləndirmə aparılmayıb", "sol tərəfə görə düzləndirmə", "eninə görə düzləndirmə", "sağ tərəfə görə düzləndirmə", "mərkəzə görə düzləndirmə"], answer: 3 },
    { question: "Word sənədində yaşıl dalğalı və ya göy xətt nəyi göstərir?", options: ["sözün çapını", "qrammatik səhvi", "orfoqrafik səhvi", "sözün silinməsini", "sözün tərcüməsini"], answer: 1 },
    { question: "MS Word mətn prosessorunda şriftin ölçüsü hansı vahidlə göstərilir?", options: ["düymlə", "bitlə", "millimetrlə", "punktla", "piksellə"], answer: 3 },
    { question: "MS Word-də siyahıların yaradılması Home (Главная) tabının hansı lent qrupunun əmri ilə yerinə yetirilir?", options: ["Editing (Peдaктирование)", "Styles (Cтили)", "Paragraph (Абзац)", "Font (Шрифт)", "Clipboard (Буфер обмена)"], answer: 2 },
    { question: "Word proqramında şablondan nə üçün istifadə olunur?", options: ["sənədin eyni hissələrini köçürmək üçün", "oxşar sənədlər yaratmaq üçün", "səhv yazılmış sözləri düzəltmək üçün", "sənədə cədvəl yerləşdirmək üçün", "sənədə qrafik yerləşdirmək üçün"], answer: 1 },
    { question: "Word sənədində qırmızı dalğalı xətt nəyi göstərir?", options: ["sözün çapını", "orfoqrafik səhvi", "qrammatik səhvi", "sözün silinməsini", "sözün tərcüməsini"], answer: 1 },
    { question: "Equation proqramı ..... üçün nəzərdə tutulmuşdur.", options: ["füqurlu mətnlərin təşkili", "riyazi hesablamaların aparılması", "cədvəllərin təşkili", "diaqramların qurulması", "mürəkkəb riyazi düsturların yazılması"], answer: 4 },
    { question: "Word proqramının əsas funksiyası nədir?", options: ["Verilənlər bazasının yaradılması və idarə edilməsi", "Mürəkkəb mətn sənədlərinin yaradılması", "Qrafik informasiyanın redaktə olunması", "Elektron cədvəllərin hazırlanması və email", "Yeni proqramların işlənməsi"], answer: 1 },
    { question: "Mətn fraqmentləri, şəkil, cədvəl və s. .......... vasitəsilə sənədlər arasında göndərilə bilər.", options: ["pəncərələr", "mübadilə buferi", "piktoqramlar", "fayl sistemi", "qovluqlar"], answer: 1 },
    { question: "Python dilində yazılmış ifadənin qiymətini tapın: x=37/9+37%9", options: ["7", "9", "4", "6", "5"], answer: 4 },
    { question: "Python dilində yazılmış ifadənin qiymətini tapın: x=189%100", options: ["90", "1", "189", "89", "100"], answer: 3 },
    { question: "Python dilində yazılmış ifadənin qiymətini tapın: x=7//5+4%3", options: ["0", "1", "2", "11", "3"], answer: 2 },
    { question: "Python dilində x%y nəyi hesablayır?", options: ["ədədin tam hissəsini və qalığını", "x ədədinin y ədədinə bölünməsindən alınan tam hissəni", "x ədədinin kəsr hissəsinin mərtəbəliliyinin y qədər yuvarlaqlaşmasını", "x ədədinin y ədədinə bölünməsindən alınan nəticəni", "x ədədinin y ədədinə bölünməsindən alınan qalığı"], answer: 4 },
    { question: "Python dilində x//y nəyi hesablayır?", options: ["x ədədinin kəsr hissəsinin mərtəbəliliyinin y qədər yuvarlaqlaşmasını", "x ədədinin y ədədinə bölünməsindən alınan qalığı", "ədədin tam hissəsini və qalığını", "x ədədinin y ədədinə bölünməsindən alınan tam hissəni", "x ədədinin y ədədinə bölünməsindən alınan nəticəni"], answer: 3 },
    { question: "input() funksiyası nə üçün istifadə edilir?", options: ["sətrin uzunluğunu tapmaq üçün", "klaviaturadan qiymət daxil etmək üçün", "ədədlərin içindən ən kiçiyini tapmaq üçün", "ədədlərin içindən ən böyüyünü tapmaq üçün", "dəyişənin tipini tapmaq üçün"], answer: 1 },
    { question: "Qiyməti rəqəm olaraq 5-ə bərabər olan dəyişən hansıdır?", options: ["x=float(5)", "x=str(5)", "x=numericl(5)", "x = 5", "x = integer(5)"], answer: 3 },
    { question: "sqrt funksiyasını hesablamaq ücün hansı kitabxana moduluna müraciət etmək lazımdır?", options: ["turtle", "return", "append", "math", "random"], answer: 3 },
    { question: "int() funksiyası nə üçün istifadə edilir?", options: ["sətir tipinə keçmək üçün", "sətrin uzunluğunu tapmaq üçün", "ədədlərin içindən ən kiçiyini tapmaq üçün", "tam ədəd tipinə keçmək üçün", "həqiqi ədəd tipinə keçmək üçün"], answer: 3 },
    { question: "str() funksiyası nə üçün istifadə edilir?", options: ["sətrin uzunluğunu tapmaq üçün", "tam ədəd tipinə keçmək üçün", "həqiqi ədəd tipinə keçmək üçün", "sətir tipinə keçmək üçün", "ədədlərin içindən ən kiçiyini tapmaq üçün"], answer: 3 },
    { question: "Python-da sabit (constant) necə təyin olunur?", options: ["Sabitlər Python-da təyin edilmir", "Sabitlər dəyişənlər kimi təyin edilir", "Sabitlər kiçik hərflərlə yazılır", "Sabitlər yalnız böyük hərflərlə yazılır", "Sabitlər _ ilə başlanır"], answer: 3 },
    { question: "Python-da hansı xüsusiyyət digər proqramlaşdırma dillərindən fərqlənir?", options: ["Python yalnız serverlər üçün istifadə olunur", "Asinxron işləməyi təklif etmir", "Təhlükəsizliyi yüksəkdir", "Yalnız obyekt yönlü proqramlaşdırma dəstəkləyir", "Python skript dilidir"], answer: 4 },
    { question: "Aşağıdakılardan hansı proqramlaşdırma dilidir?", options: ["JQUERY", "Publisher", "MySQL", "ORACLE", "Python"], answer: 4 },
    { question: "'Hello World' Python-da hansı sintaksislə yazılır?", options: ["echo(\"Hello World\");", "p(\"Hello World\")", "p.out \"Hello World\"", "echo \"Hello World\"", "print(\"Hello World\")"], answer: 4 },
    { question: "Python hansı proqramlaşdırma paradigmalarından istifadə edir?", options: ["Yalnız prosedural proqramlaşdırma", "Təkcə obyekt yönümlü proqramlaşdırma", "Sadə funksional proqramlaşdırma", "Obyekt yönümlü və funksional proqramlaşdırma", "Yalnız struktural proqramlaşdırma"], answer: 3 },
    { question: "Python-da əməliyyatlar hansı əmr dilində icra edilir?", options: ["Kompilyasiya", "Sözlü", "İnterpretasiya", "Assembly", "Maşın dili"], answer: 2 },
    { question: "Python proqramlaşdırma dilinin əsas proqram pəncərəsinin adı nədir?", options: ["Ecilips", "Sublime", "Netbeans", "IDLE", "VisualStudio"], answer: 3 },
    { question: "float() funksiyası nə üçün istifadə edilir?", options: ["ədədlərin içindən ən kiçiyini tapmaq üçün", "sətrin uzunluğunu tapmaq üçün", "tam ədəd tipinə keçmək üçün", "sətir tipinə keçmək üçün", "həqiqi ədəd tipinə keçmək üçün"], answer: 4 },
    { question: "Python proqramlaşdırma dili kim tərəfindən yaradılmışdır", options: ["Robert Gentelmen", "Ross İhaka", "James Gosling", "Bjarne Stroustrup", "Guido van Rossum"], answer: 4 },
    { question: "Python dili hansı növ verilənlər tipini dəstəkləyir?", options: ["Heç biri", "Yalnız boolean", "Yalnız ədədlər", "Yalnız sətirlər", "ədədlər, sətirlər və digər verilənlər tipləri"], answer: 4 },
    { question: "Aşağıdakılardan hansı mətn prosessorudur?", options: ["WinRar", "Paint", "Excel", "Word", "FoxPro"], answer: 3 },
    { question: "Mətnin redaktə olunması dedikdə, nə başa düşülür (Word)?", options: ["mövcud mətnin xarici yaddaş daşıyıcılarından oxunması", "mətnin kompüter şəbəkəsi vasitəsilə ötürülməsi prosesi", "mövcud mətndə dəyişikliklər edilməsi", "mətnin diskdə mətn faylı kimi saxlanması", "mətnin cədvəl formasına salınması"], answer: 2 },
    { question: "Aşağıdakılardan hansı Home (Главная/Ev) lent tabına aid deyil (Word)?", options: ["Şriftin ölçüsünün dəyişdirilməsi", "Mətnə şəkillərin əlavə olunması", "Mətnin sola düzləndirilməsi", "Abzaslararası məsafələrin təyini", "Şriftin rənginin dəyişdirilməsi"], answer: 1 },
    { question: "İxtiyari mətn fraqmentinin surətinin çıxarılması üçün hansı əməliyyatı yerinə yetirmək lazımdır (Word)?", options: ["mətn hissəsini qeyd edib müvafiq tabdan Cut əmrini seçmək", "mətn hissəsini qeyd edib müvafiq tabdan Copy əmrini seçmək", "mətn hissəsini qeyd edib, müvafiq tabdan Cut əmrini seçmək, kursoru lazımi yerdə yerləşdirib Paste əmrini yerinə yetirmək", "müvafiq tabdan Copy əmrini seşmək, kursoru lazımi yerdə yerləşdirib Paste əmrini yerinə yetirmək", "mətn hissəsini qeyd edib müvafiq tabdan Paste əmrini seçmək"], answer: 1 },
    { question: "Ctrl + F kombinasiyasının funksiyası nədir (Word)?", options: ["mətn fraqmentini formatlaşdırmaq", "sənədin növbəti səhifəsinə keçid", "mətn fraqmentini əvəz etmək", "mətn fraqmentini axtarmaq", "sənədin əvvəlki səhifəsinə keçid"], answer: 3 },
    { question: "Word mətn prosessorunda Copy əmri ... sonra verilə bilər.", options: ["səhifənin parametrləri təyin olunduqdan", "faylın çapından", "kursorun göstəricisi tələb olunan yerə gətirildikdən", "fayl yaddaşa göndərildikdən", "mətn fraqmenti qeyd edildikdən"], answer: 4 },
    { question: "Klaviaturadan daxil edilmiş simvolun mövqeyi ... təyin olunur (Word).", options: ["daxil edilən koordinatlarla", "kursorun mövqeyi ilə", "ixtiyari qaydada", "səhifənin nömrəsi ilə", "əvvəlcə daxil edilmiş hərfin vəziyyəti ilə"], answer: 1 },
    { question: "Klaviaturada Home düyməsinin təyinatı nədir (Word)?", options: ["Boş məsafə əlavə edir", "Kursoru birbaşa sətrin əvvəlinə keçirir", "Kursoru birbaşa mətnin əvvəlinə keçirir", "Kursorun yerini sənədin sonuna dəyişir", "Baş hərflərə keçir"], answer: 1 },
    { question: "Word sənədində klaviaturadan Сtrl+Enter düymələr kombinasiyası basıldıqda nə baş verir?", options: ["kursor növbəti bölmənin sonuna keçir", "kursordan sonrakı hissə yeni səhifəyə keçir", "mətn hecalara bölünür", "mətn tamamilə qey olunur", "mətn yeni abzasa ayrılır"], answer: 1 }
    ],
  "Mühasibat Uçotu": [
    { question: "Mühasibat uçotunda tətbiq edilən hesablar necə qruplaşır?", options: ["İqtisadi hərəkətinə görə; iqtisadi quruluşuna görə", "İqtisadi məzmununa görə; iqtisadi bərabərliyinə görə", "Təyinatı və quruluşuna görə; iqtisadi bərabərliyinə görə", "İqtisadi məzmununa görə; təyinatı və quruluşuna görə", "Təyinatı görə; hesabların hesablaşmasına görə"], answer: 3 },
    { question: "Aktiv hesabların debet dövriyyəsi nəyi göstərir?", options: ["Əmlakın azalmasını", "Əmlakın artmasını", "Öhdəliklərin artmasını", "Öhdəliklərin azalmasını", "Kapitalın artmasını"], answer: 1 },
    { question: "Balans hesabatı hansı tarixə tərtib edilir?", options: ["İlin əvvəlinə", "Hesabat dövrünün sonuna", "Hesabat dövrünün əvvəlinə", "İstənilən tarixə", "Rübün əvvəlinə"], answer: 1 },
    { question: "Passiv hesabların kredit dövriyyəsi nəyi göstərir?", options: ["Mənbənin azalmasını", "Mənbənin artmasını", "Əmlakın artmasını", "Əmlakın azalmasını", "Kapitalın azalmasını"], answer: 1 },
    { question: "İkili yazılış prinsipi nəyi bildirir?", options: ["Hər əməliyyat bir hesabda qeyd olunur", "Hər əməliyyat iki hesabda eyni məbləğdə qeyd olunur", "Hər əməliyyat üç hesabda qeyd olunur", "Əməliyyatlar yalnız aktiv hesablarda qeyd olunur", "Əməliyyatlar yalnız passiv hesablarda qeyd olunur"], answer: 1 },
    { question: "Mühasibat balansının tərəfləri arasında bərabərlik necədir?", options: ["Aktiv > Passiv", "Aktiv < Passiv", "Aktiv = Passiv", "Aktiv ≠ Passiv", "Aktiv = 2 × Passiv"], answer: 2 },
    { question: "Amortizasiya nədir?", options: ["Əmlakın satışı", "Əsas vəsaitlərin dəyərinin hissə-hissə xərclərə köçürülməsi", "Kapitalın artırılması", "Borcun ödənilməsi", "Malların alınması"], answer: 1 },
    { question: "Debitor borcu nədir?", options: ["Müəssisənin üçüncü şəxslərə olan borcu", "Üçüncü şəxslərin müəssisəyə olan borcu", "Bank krediti", "Vergi borcu", "Əmək haqqı borcu"], answer: 1 },
    { question: "Kreditor borcu nədir?", options: ["Müəssisənin üçüncü şəxslərə olan borcu", "Üçüncü şəxslərin müəssisəyə olan borcu", "Müştərilərin borcu", "Müəssisənin bank borcudur", "İşçilərin borcu"], answer: 0 },
    { question: "Xalis mənfəət necə hesablanır?", options: ["Gəlir - Xərc", "Gəlir - Xərc - Vergi", "Gəlir + Xərc", "Xərc - Gəlir", "Gəlir × Vergi"], answer: 1 },
    { question: "Mühasibat uçotunun əsas funksiyası hansıdır?", options: ["İstehsalın artırılması", "İqtisadi fəaliyyətin qeydiyyatı, ölçülməsi, sistemləşdirilməsi", "Marketinq strategiyasının hazırlanması", "Satışın artırılması", "Reklam"], answer: 1 },
    { question: "Hesablar planı nədir?", options: ["Mühasibat hesablarının siyahısı", "Malların qiyməti", "Ödəniş cədvəli", "Büdcə planı", "İstehsal planı"], answer: 0 },
    { question: "Maliyyə hesabatlarına aiddir?", options: ["Yalnız balans", "Balans, mənfəət və zərər hesabatı, pul vəsaitlərinin hərəkəti", "Yalnız mənfəət hesabatı", "Yalnız audit hesabatı", "Yalnız vergi bəyannaməsi"], answer: 1 },
    { question: "Dövriyyə kapitalına daxildir?", options: ["Torpaq", "Binalar", "Xammal, hazır məhsul, debitor borcu", "Avadanlıq", "Patent"], answer: 2 },
    { question: "Əsas vəsaitlər hesabı hansı tiplidir?", options: ["Passiv", "Aktiv", "Aktiv-passiv", "Nizamlanma", "Nəticə"], answer: 1 },
    { question: "Kapital hesabı hansı tərəfdə yerləşir?", options: ["Aktivdə", "Passivdə", "Hər ikisində", "Balans xaricindədir", "Heç birində"], answer: 1 },
    { question: "Jurnal-order forması nədir?", options: ["Dövriyyə cədvəli", "Uçot registrinin bir forması", "Balans forması", "Hesabat forması", "Vergi forması"], answer: 1 },
    { question: "İlkin sənəd nədir?", options: ["Hesabat", "Əməliyyatın birbaşa sənədləşdirildiyi sənəd", "Müqavilə", "Hesab-faktura", "Bank çıxarışı"], answer: 1 },
    { question: "Uçot siyasəti nədir?", options: ["Mühasibat prinsipləri toplusu", "Müəssisənin uçotu aparmaq üçün seçdiyi üsullar toplusu", "Vergi strategiyası", "Audit planı", "Maliyyə planı"], answer: 1 },
    { question: "Konsolidasiya edilmiş uçot nədir?", options: ["Bir müəssisənin uçotu", "Bir neçə müəssisənin vahid uçotda birləşdirilməsi", "Vergi uçotu", "Büdcə uçotu", "Sığorta uçotu"], answer: 1 },
    { question: "Smetanın rolü nədir?", options: ["Satışın artırılması", "Gəlir və xərclərin planlaşdırılması", "Audit aparılması", "İstehsalın dayandırılması", "Kapitalın azaldılması"], answer: 1 },
    { question: "Mühasibat uçotu hansı prinsipə əsaslanır?", options: ["İqtisadi səmərəlilik", "Qoşa yazılış, davamlılıq, konservatizm", "Bazar tələbi", "İstehsal həcmi", "Vergitutma"], answer: 1 },
    { question: "Müflis elan edilmə hansı vəziyyəti göstərir?", options: ["Mənfəətin artması", "Müəssisənin borclarını ödəyə bilməməsi", "Yeni müəssisə açılması", "Kapitalın artırılması", "Satışın artması"], answer: 1 },
    { question: "Pul vəsaitlərinin hərəkəti hesabatı nə üçündür?", options: ["Əmlak qiymətləndirilməsi", "Pul daxilolmaları və ödənişlərinin göstərilməsi", "Mənfəətin hesablanması", "Vergi hesablanması", "Kapital artımı"], answer: 1 },
    { question: "Vergi uçotu ilə mühasibat uçotu arasındakı fərq nədir?", options: ["Fərq yoxdur", "Vergi uçotu vergi qanunlarına, mühasibat uçotu mühasibat standartlarına əsaslanır", "Mühasibat uçotu daha sadədir", "Vergi uçotu daha əhatəlidir", "Eynidir, sadəcə adları fərqlidir"], answer: 1 },
    { question: "İnventar siyahıyaalma nə deməkdir?", options: ["Malların satılması", "Əmlak və öhdəliklərin faktiki mövcudluğunun yoxlanılması", "Hesabatın hazırlanması", "Sənədlərin arxivlənməsi", "Vergi ödənilməsi"], answer: 1 },
    { question: "Hesab-faktura nədir?", options: ["Bank sənədi", "Mal və ya xidmət üçün ödəniş tələbi olan sənəd", "Müqavilə", "Vergi bəyannaməsi", "İş sərəncamı"], answer: 1 },
    { question: "Nizamnamə kapitalı nədir?", options: ["Bütün mənfəət", "Müəssisənin yaradılması zamanı qoyulmuş ilkin kapital", "Bank krediti", "Dövlət subsidiyası", "Satış gəliri"], answer: 1 },
    { question: "Qiymətli kağızlar uçotuna daxildir?", options: ["Torpaq", "Aksiyalar, istiqrazlar, veksellər", "Avadanlıq", "Xammal", "Hazır məhsul"], answer: 1 },
    { question: "Kassa kitabı nədir?", options: ["Mühasibat kitabı", "Kassa əməliyyatlarının qeyd olunduğu uçot registri", "Hesabat forması", "Sifariş kitabı", "Anbar kitabı"], answer: 1 },
    { question: "Mühasibat uçotunun predmeti nədir?", options: ["Yalnız pul vəsaitləri", "Müəssisənin iqtisadi vəsaitləri və onların mənbələri, habelə əməliyyatları", "Yalnız borclular", "Yalnız əsas vəsaitlər", "Yalnız dövriyyə vəsaitləri"], answer: 1 },
    { question: "Audit nədir?", options: ["Malların satışı", "Maliyyə hesabatlarının müstəqil yoxlanılması", "Mühasibat uçotunun aparılması", "Vergi bəyannaməsinin doldurulması", "Büdcənin planlaşdırılması"], answer: 1 },
    { question: "Subhesab nədir?", options: ["Əsas hesabın analitik ayrıntısı", "Ayrı bir hesab növü", "Balans sənədi", "Hesabat növü", "Büdcə bölməsi"], answer: 0 },
    { question: "Nağd pul əməliyyatları kim tərəfindən aparılır?", options: ["Baş mühasib", "Müdir", "Kassir", "Anbardar", "Satıcı"], answer: 2 },
  ],

  "İqtisadiyyat": [
    { question: "İqtisadiyyat nəyi öyrənir?", options: ["Yalnız pul əməliyyatlarını", "Məhdud resursların paylanması ilə bağlı seçimləri", "Yalnız ticarəti", "Coğrafi amilləri", "Tarixi hadisələri"], answer: 1 },
    { question: "Tələb qanunu nə bildirir?", options: ["Qiymət artdıqca tələb artır", "Qiymət artdıqca tələb azalır", "Qiymət sabit qalır", "Tələb təklifdən asılı deyil", "Qiymət azaldıqca tələb azalır"], answer: 1 },
    { question: "Təklif qanunu nə bildirir?", options: ["Qiymət artdıqca təklif azalır", "Qiymət artdıqca təklif artır", "Qiymət sabit qalır", "Təklif tələbdən asılı deyil", "Qiymət azaldıqca təklif artır"], answer: 1 },
    { question: "Bazar tarazlığı nə zaman yaranır?", options: ["Tələb > Təklif", "Tələb < Təklif", "Tələb = Təklif", "Qiymət maksimum olanda", "Qiymət minimum olanda"], answer: 2 },
    { question: "ÜDM nədir?", options: ["Ölkənin xarici borcu", "Ölkədə müəyyən dövrdə istehsal edilmiş bütün mal və xidmətlərin dəyəri", "Dövlət büdcəsi", "Valyuta ehtiyatı", "İxrac həcmi"], answer: 1 },
    { question: "İnflyasiya nədir?", options: ["Qiymətlərin azalması", "Qiymətlərin ümumi səviyyəsinin artması", "İstehsalın artması", "İşsizliyin azalması", "Valyutanın möhkəmlənməsi"], answer: 1 },
    { question: "Deflyasiya nədir?", options: ["Qiymətlərin artması", "Qiymətlərin ümumi səviyyəsinin azalması", "Büdcə kəsiri", "Ticarət balansının artması", "Valyutanın zəifləməsi"], answer: 1 },
    { question: "Məcburi işsizlik nədir?", options: ["İş tapmaq istəməyənlər", "İş tapmaq istəyib, lakin tapa bilməyənlər", "Tətildə olanlar", "Xəstə olanlar", "Tələbələr"], answer: 1 },
    { question: "Fiskal siyasət nədir?", options: ["Mərkəzi bankın siyasəti", "Dövlətin vergi və xərclər vasitəsilə iqtisadiyyata müdaxiləsi", "Xarici ticarət siyasəti", "Miqrasiya siyasəti", "Sığorta siyasəti"], answer: 1 },
    { question: "Monetar siyasət nədir?", options: ["Dövlətin vergi siyasəti", "Mərkəzi bankın pul kütləsini idarə etməsi", "Ticarət siyasəti", "Miqrasiya siyasəti", "Sosial siyasət"], answer: 1 },
    { question: "Tələbin qiymət elastikliyi nədir?", options: ["Tələb artımının miqdarı", "Tələb miqdarının qiymət dəyişikliklərinə həssaslığı", "Qiymət artımının sürəti", "İstehsalçı gəliri", "Bazar payı"], answer: 1 },
    { question: "Fayda nədir?", options: ["İstehsal xərci", "Malın istehlakından əldə edilən məmnuniyyət", "Satış qiyməti", "Mənfəət", "Vergi"], answer: 1 },
    { question: "Mövsümi işsizlik nəyə görə yaranır?", options: ["Texnoloji dəyişikliklərə görə", "İqtisadiyyatın mövsümi xarakter daşımasına görə", "Əmək haqlarının artmasına görə", "İstehsalın azalmasına görə", "Xarici rəqabətə görə"], answer: 1 },
    { question: "Makroiqtisadiyyat nəyi öyrənir?", options: ["Ayrı-ayrı firmalar", "Ölkənin bütövlükdə iqtisadi göstəricilərini", "Fərdi istehlakçılar", "Bir sektoru", "Xarici ticarəti"], answer: 1 },
    { question: "Mikroiqtisadiyyat nəyi öyrənir?", options: ["Bütün ölkəni", "Ayrı-ayrı iqtisadi subyektlərin davranışını", "Beynəlxalq ticarəti", "Pul siyasətini", "Dövlət büdcəsini"], answer: 1 },
    { question: "Mükəmməl rəqabət bazarının xüsusiyyəti nədir?", options: ["Az satıcı", "Çox sayda satıcı, homojen məhsul, azad giriş-çıxış", "Qiymət ayrı-seçkilik", "Reklam üstünlüyü", "Patentlər"], answer: 1 },
    { question: "Monopoliya nədir?", options: ["Çoxlu satıcı", "Bazarda tək satıcının olması", "İki satıcı", "Dövlət müdaxiləsi", "Azad ticarət"], answer: 1 },
    { question: "Oliqopoliya nədir?", options: ["Bir satıcı", "Bir neçə böyük satıcının bazar payını tutması", "Çox sayda satıcı", "Dövlət inhisarı", "Azad rəqabət"], answer: 1 },
    { question: "İstehlakçı artığı nədir?", options: ["İstehsalçı mənfəəti", "Alıcının ödəmək istədiyi qiymətlə ödədiyi qiymət arasındakı fərq", "Bazardakı artıq məhsul", "Vergi gəliri", "Büdcə artığı"], answer: 1 },
    { question: "Əmək haqqının minimum həddi nəyə görə müəyyən edilir?", options: ["İstehsalçı mənfəəti üçün", "İşçilərin minimum yaşayış standartını qorumaq üçün", "İnflyasiyanı artırmaq üçün", "İşsizliyi artırmaq üçün", "Xarici investisiya cəlb etmək üçün"], answer: 1 },
    { question: "Sabit xərc nədir?", options: ["İstehsal həcminə görə dəyişən xərc", "İstehsal həcmindən asılı olmayan xərc", "Xammal xərci", "Enerji xərci", "Əmək haqqı"], answer: 1 },
    { question: "Dəyişkən xərc nədir?", options: ["İstehsal həcmindən asılı olmayan xərc", "İstehsal həcminə görə dəyişən xərc", "Amortizasiya", "İcarə", "Sığorta"], answer: 1 },
    { question: "Miqyas qənaəti nədir?", options: ["Kiçik miqyasda istehsalın üstünlüyü", "İstehsal həcmi artdıqca vahid xərcin azalması", "İstehsalın dayandırılması", "Bazardan çıxılması", "Qiymət artırılması"], answer: 1 },
    { question: "Əvəzedici mallar nədir?", options: ["Birlikdə istifadə olunan mallar", "Biri digərinin yerini tuta bilən mallar", "Bir-birisiz istifadə edilə bilməyən mallar", "Eyni qiymətli mallar", "Eyni keyfiyyətli mallar"], answer: 1 },
    { question: "Tamamlayıcı mallar nədir?", options: ["Biri digərinin yerini tutan mallar", "Birlikdə istifadə olunan mallar", "Rəqib mallar", "Eyni qiymətli mallar", "Lüks mallar"], answer: 1 },
    { question: "Normal mal nədir?", options: ["Gəlir artdıqca tələb azalan mal", "Gəlir artdıqca tələb artan mal", "Qiymətdən asılı olmayan mal", "Tələbsiz mal", "İnferior mal"], answer: 1 },
    { question: "İnferior mal nədir?", options: ["Gəlir artdıqca tələb artan mal", "Gəlir artdıqca tələb azalan mal", "Lüks mal", "Normal mal", "Sabit tələbli mal"], answer: 1 },
    { question: "Tixenin malı nədir?", options: ["Qiymət artdıqca tələb azalan mal", "Qiymət artdıqca tələb artan mal", "Əvəzedici mal", "Normal mal", "Tamamlayıcı mal"], answer: 1 },
    { question: "Rentabellik nədir?", options: ["Ümumi xərc", "Mənfəətin gəlirə və ya kapitala olan nisbəti", "İstehsal həcmi", "Satış qiyməti", "Xərclər toplusu"], answer: 1 },
    { question: "Büdcə kəsiri nə zaman olur?", options: ["Xərclər < Gəlirlər", "Xərclər > Gəlirlər", "Xərclər = Gəlirlər", "İxrac > İdxal", "İdxal > İxrac"], answer: 1 },
    { question: "Ticarət balansı nədir?", options: ["Büdcə balansı", "İxrac və idxal arasındakı fərq", "Bank balansı", "Mühasibat balansı", "Ödəniş balansı"], answer: 1 },
    { question: "Kütləvi məhsul istehsalı nə üstünlük verir?", options: ["Daha yüksək qiymət", "Daha aşağı vahid xərci", "Daha az satış", "Daha az mənfəət", "Daha az işçi"], answer: 1 },
  ],

  "Menecment": [
    { question: "Menecment nədir?", options: ["Yalnız istehsalın idarə edilməsi", "Təşkilatın məqsədlərini gerçəkləşdirmək üçün resursların planlaşdırılması, təşkili, rəhbərliyi və nəzarəti", "Yalnız maliyyənin idarəsi", "Mühasibat prosesi", "Satış prosesi"], answer: 1 },
    { question: "İdarəetmənin əsas funksiyaları hansılardır?", options: ["Planlaşdırma, marketing, satış", "Planlaşdırma, təşkil, rəhbərlik, nəzarət", "İstehsal, satış, reklam", "Maliyyə, uçot, audit", "Kadr, hüquq, texnologiya"], answer: 1 },
    { question: "Strateji idarəetmə nədir?", options: ["Günlük əməliyyatların idarəsi", "Uzunmüddətli məqsəd və strategiyaların müəyyənləşdirilməsi", "Yalnız maliyyə idarəsi", "Kadrların idarəsi", "Texnologiya idarəsi"], answer: 1 },
    { question: "SWOT analizi nəyi əhatə edir?", options: ["Satış, Qazan, Əldə et, Transfer", "Güclü cəhətlər, Zəif cəhətlər, İmkanlar, Təhdidlər", "Strateji, Ağıllı, Oriyentasiya, Texnologiya", "Bazar, Rəqabət, Xərc, Keyfiyyət", "Sürət, Çeviklik, Keyfiyyət, Texnologiya"], answer: 1 },
    { question: "Liderlik nədir?", options: ["Yalnız rəsmi vəzifə sahibi olmaq", "Başqalarına təsir etmək və onları məqsədə doğru istiqamətləndirmək bacarığı", "Yalnız əmr vermək", "Yalnız nəzarət etmək", "Yalnız planlaşdırmaq"], answer: 1 },
    { question: "Motivasiya nədir?", options: ["İşçiləri cəzalandırmaq", "İşçiləri məqsədlər uğrunda fəaliyyətə sövq edən daxili və xarici amillər", "Yalnız pul mükafatı", "Yalnız terfi", "Yalnız nəzarət"], answer: 1 },
    { question: "Maslow-un ehtiyaclar iyerarxiyası neçə səviyyədən ibarətdir?", options: ["3", "4", "5", "6", "7"], answer: 2 },
    { question: "Delegasiya nədir?", options: ["Vəzifənin artırılması", "Səlahiyyət və məsuliyyətin aşağı vəzifəlilərə verilməsi", "İşdən çıxarılma", "Mükafat verilməsi", "Cəza tətbiqi"], answer: 1 },
    { question: "Kommunikasiya idarəetmədə nə üçün vacibdir?", options: ["Sənədləşmə üçün", "Məlumat mübadiləsi, əlaqələndirmə və qərar qəbulu üçün", "Yalnız xarici əlaqələr üçün", "Yalnız maliyyə üçün", "Yalnız istehsal üçün"], answer: 1 },
    { question: "Qrup dinamikası nədir?", options: ["Fərdi davranış", "Qrup üzvlərinin bir-birinə qarşılıqlı təsiri", "Rəsmi struktur", "İerarxiya", "Büdcə planı"], answer: 1 },
    { question: "İş strukturu nədir?", options: ["Vəzifə siyahısı", "Təşkilatdakı vəzifə münasibətlərinin sistemi", "Əmək haqqı cədvəli", "Məhsul kataloqu", "Satış planı"], answer: 1 },
    { question: "Nəzarətin məqsədi nədir?", options: ["İşçiləri izləmək", "Planlaşdırılmış nəticələrin əldə edilib-edilmədiyini yoxlamaq", "Xərclərə qənaət etmək", "İş vaxtını azaltmaq", "Qazancı maksimuma çatdırmaq"], answer: 1 },
    { question: "Xarizma nədir?", options: ["Rəsmi vəzifə", "Liderlik üçün şəxsiyyətin cəlbedici keyfiyyəti", "Pul mükafatı", "Hüquqi güc", "Texniki bacarıq"], answer: 1 },
    { question: "Qərar qəbul prosesinin birinci addımı nədir?", options: ["Alternativlərin qiymətləndirilməsi", "Problemin müəyyənləşdirilməsi", "Alternativlərin seçilməsi", "Həllin tətbiqi", "Nəticənin yoxlanması"], answer: 1 },
    { question: "Layihə menecmenti nədir?", options: ["Gündəlik fəaliyyətin idarəsi", "Müvəqqəti layihəni müəyyən məqsəd üçün planlaşdırıb idarə etmək", "Müəssisənin uzunmüddətli idarəsi", "Yalnız maliyyənin idarəsi", "Yalnız kadrların idarəsi"], answer: 1 },
    { question: "Konfliktin müsbət cəhəti ola bilərmi?", options: ["Xeyr, konflikt həmişə zərərlidir", "Bəli, konflikt yeni ideyaların yaranmasına kömək edə bilər", "Yalnız xarici konfliktin müsbət cəhəti var", "Yalnız aşağı səviyyəli işçilərarası konfliktin", "Yalnız menecerlərarası konfliktin"], answer: 1 },
    { question: "İnsan resursları menecmenti nəyi əhatə edir?", options: ["Yalnız işə qəbul", "İşə qəbul, inkişaf, motivasiya, qiymətləndirmə, kompensasiya", "Yalnız əmək haqqı hesablanması", "Yalnız tərxis", "Yalnız ixtisasartırma"], answer: 1 },
    { question: "Korporativ mədəniyyət nədir?", options: ["Şirkətin binasının dizaynı", "Şirkətin dəyərləri, normaları, davranış qaydaları toplusu", "Şirkətin məhsulları", "Şirkətin logosu", "Şirkətin büdcəsi"], answer: 1 },
    { question: "Məhsulun həyat dövrü neçə mərhələdən ibarətdir?", options: ["2", "3", "4", "5", "6"], answer: 2 },
    { question: "Benchmarking nədir?", options: ["Yalnız daxili proseslərin yoxlanması", "Öz fəaliyyətini aparıcı rəqiblərlə müqayisə etmək", "Yalnız maliyyə analizi", "Müştəri şikayətlərinin analizi", "İşçilərin qiymətləndirilməsi"], answer: 1 },
    { question: "TQM nədir?", options: ["Texnoloji Qiymətləndirmə Modeli", "Ümumi Keyfiyyət Menecmenti", "Ticarət Qaydaları Məcəlləsi", "Texniki Qiymət Metodologiyası", "Transmilli Qiymət Mexanizmi"], answer: 1 },
    { question: "ERP sistemi nədir?", options: ["Elektron Rahat Proqram", "Müəssisə Resurslarının Planlaşdırılması Sistemi", "Elektron Ödəniş Rejimi", "Əmək haqlarının Proqramı", "Energetika Resurslarının Paylanması"], answer: 1 },
    { question: "Outsourcing nədir?", options: ["Daxili resursları genişləndirmək", "Müəyyən funksiyaları xarici şirkətlərə tapşırmaq", "Yeni bazar açmaq", "Yeni məhsul istehsal etmək", "Filiallar açmaq"], answer: 1 },
    { question: "Balanced Scorecard nədir?", options: ["Mühasibat cədvəli", "Müxtəlif perspektivlər üzrə fəaliyyətin ölçülməsi sistemi", "Bank hesabı", "Vergi bəyannaməsi", "Müqavilə forması"], answer: 1 },
    { question: "Qloballaşma menecmentə necə təsir edir?", options: ["Heç bir təsir etmir", "Beynəlxalq rəqabət, müxtəlif mədəniyyətlərlə iş, yeni imkanlar", "Yalnız mənfi təsir edir", "Yalnız kiçik müəssisələrə təsir edir", "Yalnız ixracatçılara təsir edir"], answer: 1 },
  ],

  "Maliyyə": [
    { question: "Maliyyə nədir?", options: ["Yalnız pul əməliyyatları", "Pul fondlarının formalaşması, bölüşdürülməsi və istifadəsi ilə bağlı münasibətlər", "Yalnız dövlət büdcəsi", "Yalnız bank fəaliyyəti", "Yalnız sığorta"], answer: 1 },
    { question: "Dövlət büdcəsi nədir?", options: ["Şirkətin maliyyə planı", "Dövlətin gəlir və xərclərini əhatə edən əsas maliyyə sənədi", "Bank balansı", "Ticarət balansı", "Sığorta fondu"], answer: 1 },
    { question: "Faiz dərəcəsi nədir?", options: ["Vergi dərəcəsi", "Kreditin istifadəsi üçün ödənilən haqqın miqdarı", "İnflyasiya dərəcəsi", "Valyuta məzənnəsi", "Divident dərəcəsi"], answer: 1 },
    { question: "Kapitalın dəyəri nədir?", options: ["Əmlakın qiyməti", "Kapitalın istifadəsi üçün ödənilən xərc", "Satış qiyməti", "İstehsal xərci", "Bazar qiyməti"], answer: 1 },
    { question: "Likvidlik nədir?", options: ["Mənfəətlilik", "Aktivlərin tez nağd pula çevrilmə qabiliyyəti", "Borcluluq nisbəti", "Rentabellik", "Kapital strukturu"], answer: 1 },
    { question: "Dividend nədir?", options: ["İstiqraz gəliri", "Aksiya sahiblərinə şirkətin mənfəətindən ödənilən pay", "Bank faizi", "Kredit ödənişi", "Vergi ödənişi"], answer: 1 },
    { question: "Aksiya nədir?", options: ["Borc sənədi", "Şirkətin kapitalında paya sahib olmağı təsdiq edən qiymətli kağız", "Bank çeki", "Müqavilə", "Hesab-faktura"], answer: 1 },
    { question: "İstiqraz nədir?", options: ["Kapital qiymətli kağızı", "Emitentin alıcı qarşısında borcunu təsdiq edən qiymətli kağız", "Dividend sənədi", "Aksiya növü", "Bank depoziti"], answer: 1 },
    { question: "Leasing nədir?", options: ["Aktivlərin satışı", "Aktivlərin icarəyə verilməsi, bəzən sonunda mülkiyyətə keçmə hüququ ilə", "Bank krediti növü", "Sığorta növü", "Fond əməliyyatı"], answer: 1 },
    { question: "Faktoring nədir?", options: ["İstehsal prosesi", "Debitor borclarının xüsusi şirkətlərə satılması", "Kredit növü", "Sığorta növü", "Lizinq növü"], answer: 1 },
    { question: "Fond birjası nədir?", options: ["Bank filialı", "Qiymətli kağızların alınıb-satıldığı təşkilatlanmış bazar", "Sığorta şirkəti", "Xarici valyuta bazarı", "Əmtəə bazarı"], answer: 1 },
    { question: "Gəlir vergisi nədir?", options: ["Dövriyyəyə görə vergi", "Fiziki şəxslərin gəlirindən alınan vergi", "Əmlaqa görə vergi", "İdxal vergisi", "Əlavə dəyər vergisi"], answer: 1 },
    { question: "ƏDV nədir?", options: ["Əmək haqqından vergi", "Malların istehsalı və satışının hər mərhələsində yaranan dəyərə görə vergi", "Mənfəət vergisi", "Gömrük vergisi", "Torpaq vergisi"], answer: 1 },
    { question: "Maliyyə riski nədir?", options: ["İstehsal riski", "Müəssisənin maliyyə öhdəliklərini yerinə yetirə bilməmə riski", "Texnoloji risk", "Bazar riski", "Hüquqi risk"], answer: 1 },
    { question: "Portfel diversifikasiyası nəyə xidmət edir?", options: ["Gəliri maksimuma çatdırır", "Müxtəlif aktivlərə investisiya yerləşdirərək riski azaldır", "Vergiləri azaldır", "Likvifliyi artırır", "Kapitalı azaldır"], answer: 1 },
    { question: "Pul bazarı nədir?", options: ["Uzunmüddətli maliyyə aləti bazarı", "Qısamüddətli borc alətlərinin alınıb-satıldığı bazar", "Əmtəə bazarı", "Valyuta bazarı", "Fond bazarı"], answer: 1 },
    { question: "Kapital bazarı nədir?", options: ["Qısamüddətli borc bazarı", "Uzunmüddətli maliyyə alətlərinin bazarı", "Pul bazarı", "Əmtəə bazarı", "Sığorta bazarı"], answer: 1 },
    { question: "Xalis cari dəyər (NPV) nədir?", options: ["Ümumi gəlir", "Gələcək pul axınlarının cari dəyərinin ilkin investisiyadan çıxılması", "Mənfəət nisbəti", "Gəlirlilik indeksi", "Geri qaytarılma müddəti"], answer: 1 },
    { question: "Daxili gəlirlilik norması (IRR) nədir?", options: ["Xarici faiz dərəcəsi", "NPV-ni sıfıra bərabər edən diskont dərəcəsi", "Minimum faiz dərəcəsi", "Bank faizi", "İnflyasiya dərəcəsi"], answer: 1 },
    { question: "Maliyyə levereci nədir?", options: ["İstehsal həcmi artımı", "Borc kapitalından istifadənin öz kapitalına gəliri necə artırdığı", "Dividend siyasəti", "Amortizasiya", "Aktivlərin növü"], answer: 1 },
    { question: "Kredit reytinqi nədir?", options: ["Şirkətin bazar qiyməti", "Borcalanın kredit öhdəliklərini yerinə yetirmə qabiliyyətinin qiymətləndirilməsi", "Dividend miqdarı", "Satış həcmi", "Mənfəət marjası"], answer: 1 },
    { question: "Maliyyə planlaşdırması nədir?", options: ["Yalnız büdcə hazırlamaq", "Gəlir, xərc, investisiya və maliyyələşmə mənbələrinin müəyyənləşdirilməsi", "Yalnız kredit götürmək", "Yalnız vergi hesablamaq", "Yalnız gəlir artırmaq"], answer: 1 },
    { question: "Maliyyə hesabatlarının istifadəçiləri kimdir?", options: ["Yalnız mühasibatlıq şöbəsi", "İnvestorlar, kreditçilər, idarəçilər, tənzimləyicilər", "Yalnız vergi orqanları", "Yalnız banklar", "Yalnız müştərilər"], answer: 1 },
    { question: "Sığorta nədir?", options: ["Mənfəətin bölüşdürülməsi", "Gözlənilməz itkilərə qarşı maliyyə müdafiəsi", "Kredit növü", "İnvestisiya növü", "Fond növü"], answer: 1 },
  ],

  "Statistika": [
    { question: "Statistika nədir?", options: ["Yalnız rəqəm toplama", "Məlumatların toplanması, təhlili, şərhi və təqdim edilməsi elmi", "Yalnız ehtimal hesabı", "Yalnız cədvəl hazırlamaq", "Yalnız qrafik çizmək"], answer: 1 },
    { question: "Orta ədəd necə hesablanır?", options: ["Ən böyük dəyər - Ən kiçik dəyər", "Bütün dəyərlərin cəminin sayına bölünməsi", "Yalnız ən çox təkrarlanan dəyər", "Ortadakı dəyər", "Cəm × say"], answer: 1 },
    { question: "Mediana nədir?", options: ["Ən çox təkrarlanan dəyər", "Sıralanmış məlumat sırasının ortadakı dəyəri", "Orta ədəd", "Maksimum dəyər", "Minimum dəyər"], answer: 1 },
    { question: "Moda nədir?", options: ["Orta ədəd", "Ən çox təkrarlanan dəyər", "Mediana", "Maksimum dəyər", "Dispersiya"], answer: 1 },
    { question: "Dispersiya nəyi ölçür?", options: ["Mərkəzi meyl", "Dəyərlərin orta ədəddən sapma dərəcəsini", "Məlumatların toplanma üsulunu", "Minimum dəyəri", "Maksimum dəyəri"], answer: 1 },
    { question: "Standart sapma nədir?", options: ["Dispersiyanın özü", "Dispersiyanın kvadrat kökü", "Orta ədəd", "Mediana", "Moda"], answer: 1 },
    { question: "Korrelyasiya nəyi ölçür?", options: ["İki dəyişən arasındakı asılılığın istiqaməti və gücü", "Orta ədəd", "Dispersiya", "Məlumat dəqiqliyi", "Ehtimal"], answer: 0 },
    { question: "Regressiya analizi nəyə xidmət edir?", options: ["Məlumat toplanması", "Bir dəyişənin başqa dəyişəndən asılılığını modelləşdirmək", "Dispersiya hesablanması", "Ehtimal hesablanması", "Mediana tapılması"], answer: 1 },
    { question: "Ehtimal nədir?", options: ["Hadisənin baş vermə tezliyi", "Hadisənin baş vermə ehtimalının ölçüsü", "Statistik sapma", "Orta dəyər", "Dispersiya"], answer: 1 },
    { question: "Seçmə nədir?", options: ["Bütün əhali", "Ümumi kütlənin nümayəndəlik edən bir hissəsi", "Yalnız maksimum dəyərlər", "Yalnız minimum dəyərlər", "Bütün dəyərlər"], answer: 1 },
    { question: "Hipotez yoxlanması nədir?", options: ["Məlumat toplanması", "Statistik fərziyyənin doğru olub-olmadığının yoxlanılması", "Qrafik hazırlanması", "Cədvəl hazırlanması", "Orta hesablanması"], answer: 1 },
    { question: "Konfidensiya intervalı nədir?", options: ["Maksimum dəyər aralığı", "Parametrin müəyyən ehtimalla daxilə düşdüyü aralıq", "Dispersiya", "Standart sapma", "Moda aralığı"], answer: 1 },
    { question: "Variasiya əmsalı nəyə görə istifadə olunur?", options: ["Orta hesablamaq üçün", "Müxtəlif ölçü vahidli topluları müqayisə etmək üçün", "Dispersiya hesablamaq üçün", "Mediana tapmaq üçün", "Moda tapmaq üçün"], answer: 1 },
    { question: "Çoxlu xətti regressiya neçə müstəqil dəyişən ehtiva edir?", options: ["Yalnız bir", "İki və ya daha çox", "Heç biri", "Yalnız iki", "Yalnız üç"], answer: 1 },
    { question: "Zaman sırası nədir?", options: ["Təsadüfi məlumatlar", "Ardıcıl vaxt nöqtələrindəki ölçümlər toplusu", "Seçmə növü", "Dispersiya növü", "Ehtimal növü"], answer: 1 },
    { question: "İndeks nədir?", options: ["Tam dəyər", "Müxtəlif dövrlərdə dəyişənin nisbi dəyişimini ölçən kəmiyyət", "Orta dəyər", "Standart sapma", "Dispersiya"], answer: 1 },
    { question: "Çoxluq nədir?", options: ["Seçmə", "Araşdırılan bütün elementlər toplusu", "Dispersiya", "Mediana", "Ehtimal"], answer: 1 },
    { question: "I növ səhv nədir?", options: ["Yanlış hipotezi qəbul etmək", "Doğru hipotezi rədd etmək", "Nümunə götürmək", "Dispersiya hesablamaq", "Korrelyasiya tapmaq"], answer: 1 },
    { question: "II növ səhv nədir?", options: ["Doğru hipotezi rədd etmək", "Yanlış hipotezi qəbul etmək", "Nümunə götürmək", "Orta hesablamaq", "Moda tapmaq"], answer: 1 },
    { question: "p-dəyər nədir?", options: ["Ehtimal intervalı", "Müşahidə edilmiş nəticənin null hipotez altında baş vermə ehtimalı", "Dispersiya dəyəri", "Orta dəyər", "Moda dəyəri"], answer: 1 },
    { question: "Variasiya silsiləsi nədir?", options: ["Sıralanmış məlumat", "Dəyişənin minimumdan maksimuma kimi bütün dəyərlərinin cədvəli", "Dispersiya cədvəli", "Ehtimal cədvəli", "Korrelyasiya cədvəli"], answer: 1 },
    { question: "Dinamika sırası nədir?", options: ["Territorial məlumatlar", "Eyni hadisənin ardıcıl zaman dövrlərindəki dəyərləri", "Seçmə növü", "Dispersiya növü", "Ehtimal növü"], answer: 1 },
    { question: "Kənar dəyər (outlier) nədir?", options: ["Orta dəyər", "Digər dəyərlərdən kəskin fərqlənən dəyər", "Minimum dəyər", "Maksimum dəyər", "Moda dəyəri"], answer: 1 },
    { question: "Normal paylanma hansı formaya malikdir?", options: ["Düzbucaqlı", "Zəng şəkli", "Üçbucaq", "Dairə", "Xətti"], answer: 1 },
  ],

};
